[package]
name = "virtio_gpu"
version = "0.1.0"
edition = "2024"
build = "../../build.rs"

[lib]
crate-type = ["dylib"]

[dependencies]
menix = { workspace = true }
virtio = { path = "../../common/virtio" }
