name: clang-format Check

on:
  pull_request:
    types: [opened, review_requested, synchronize]
    # Only trigger if C source files have been changed.
    paths:
      - "**.c"
      - "**.h"
  push:
    branches:
      - main

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Filter only files changed by the PR.
      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: csv
          filters: |
            c:
              - '**.c'
            h:
              - '**.h'
      # Check code.
      - name: Run clang-format style check for C sources.
        if: steps.filter.outputs.c == 'true'
        uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: ${{ steps.filter.outputs.c_files }}
          style: file
      - name: Run clang-format style check for C headers.
        if: steps.filter.outputs.h == 'true'
        uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: ${{ steps.filter.outputs.h_files }}
          style: file
